language: node_js
node_js:
  - stable
  - '10'
  - '8'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
install:
  - yarn global add codecov
  - yarn install
before_script:
  - yarn run test
script:
  - yarn run build
deploy:
  provider: npm
  email: amirhosseinab@outlook.com
  api_key:
    secure: rV0af7t3N24FeM8DhNbb43j0Sjc3uq1grWyLTMxlts5ML312bw1MDNIV6uPhN/TYU6UCtv1k+6EzcFVjPzsAfy+JwOmwx/ms8QG2PL3IHFVz+jCgC7C5PTvC8i+ydnOFsZyTk3gdW/t+jAcCOrCvpSkaZV4j7QS5CKuHMx0W5oNlrRkrnmuIi08mRcBGZ/F5OxOSODGe1lmbAge81YxaoDxZ7PhRUpjnhFFc8G5Fcs9Q4nRe9b5FiobUKN+EpP/rCPgnSlXp9BSt05kSaIuMS5lO2FB/FnjoM452W6i0rgULh8os1R9G1VbFf2bMQWt26G7AFAgLDs3s2bCX9HxsDVnUVIQceU+A0GKIcGhWyXMApOMS7W5GTA67xTUljAVhf9oQ7h15+PZT1LvsLGAnIHStrdxWDHh2u2ltNGuW2tJX2ISC52QjwJHoxER8ZRJc5ch6E4d0H8s47x9NjksrzAOVfgZJP/SongSfaSMWFOvJHQz4tYcJlRdEAgYXfcXQpgN0eM+kp0dYxEkhthJQq7ptc0wSK7u9jYUj1dtztdSvGdtFcogF024UPpA6H/07muATaubru5xGFhAela6oi9ERwsM/yh6bN3uylAa1zzecaxABzy+A150/YQcIQfrZJeKreBZ4TU0WPjSFGl+enlD64cfV7oC3slU1OtgLptY=
  on:
    tags: true
    branch: master
  skip_cleanup: true
